#!/bin/sh
PREREQ=""
prereqs() { echo "$PREREQ"; }
case $1 in
  prereqs) prereqs; exit 0 ;;
esac

. /scripts/functions

if ! /lib/cryptsetup/scripts/g3k_luks | cryptsetup open /dev/mmcblk0p2 --type luks --allow-discards --key-file=- cryptroot; then
  panic "cryptsetup open failed"
fi
