db = db.getSiblingDB("iderms");
db.dropDatabase();
db = db.getSiblingDB("iderms");

db.createCollection('status_raw', {capped: true, size: 4000000000})
db.createCollection('monitor_raw', {capped: true, size: 100000000})
db.createCollection('status_persist_1min', {capped: true, size: 2000000000})
db.createCollection('status_persist_5min', {capped: true, size: 1000000000})
db.createCollection('status_persist_15min', {capped: true, size: 500000000})
db.createCollection('status_persist_hour', {capped: true, size: 250000000})
db.createCollection('status_persist_day', {capped: true, size: 50000000})
db.createCollection('alarm', {capped: true, size: 300000000})
db.createCollection('energy_persist_5min', {capped: true, size: 1000000000})
db.createCollection('energy_persist_15min', {capped: true, size: 500000000})
db.createCollection('energy_persist_hour', {capped: true, size: 250000000})
db.createCollection('energy_persist_day', {capped: true, size: 50000000})

db.status_raw.createIndex({did:1, timestamp:-1}, {unique:true})
db.monitor_raw.createIndex({did:1, timestamp:-1}, {unique:true})
db.status_persist_1min.createIndex({did:1, timestamp:-1}, {unique:true})
db.status_persist_5min.createIndex({did:1, timestamp:-1}, {unique:true})
db.status_persist_15min.createIndex({did:1, timestamp:-1}, {unique:true})
db.status_persist_hour.createIndex({did:1, timestamp:-1}, {unique:true})
db.status_persist_day.createIndex({did:1, timestamp:-1}, {unique:true})
db.alarm.createIndex({did:1, timestamp:-1, code:1}, {unique:true})
db.energy_persist_5min.createIndex({did:1, timestamp:-1}, {unique:true})
db.energy_persist_15min.createIndex({did:1, timestamp:-1}, {unique:true})
db.energy_persist_hour.createIndex({did:1, timestamp:-1}, {unique:true})
db.energy_persist_day.createIndex({did:1, timestamp:-1}, {unique:true})
db.cache.createIndex({did:1, prefix:1, periodType:1}, {unique:true})
db.cacheAlarm.createIndex({did:1}, {unique:true})
